# Generated by Django 5.1 on 2024-10-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_rename_question_text_quizquestion_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecategory',
            old_name='category_name',
            new_name='category',
        ),
    ]
