# Generated by Django 5.1 on 2024-11-03 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_remove_profile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_mentor',
            new_name='admin',
        ),
    ]
