# Generated by Django 5.1 on 2024-11-04 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_course_course_video_course_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='notes',
            new_name='note',
        ),
    ]
