# Generated by Django 5.1 on 2024-11-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_rename_notes_course_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_video',
        ),
        migrations.RemoveField(
            model_name='course',
            name='note',
        ),
    ]
