# Generated by Django 5.1 on 2024-11-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_rename_reviewer_review_user_alter_review_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
