# Generated by Django 5.1 on 2024-11-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_remove_profile_course_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course_enrolled',
            field=models.ManyToManyField(blank=True, to='adminpanel.course'),
        ),
    ]
