# Generated by Django 5.1 on 2024-11-18 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0025_coursecontent_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time_limit',
            field=models.DurationField(default=datetime.timedelta(days=30)),
        ),
    ]
